spring.application.name=java-dictionary
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/java_dictionary
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.sql.init.mode=always
# Logging levels
logging.level.root=WARN
logging.level.com.noahparknguyen.javadictionary=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
# Shows SQL bind parameter values - useful for debugging, disable in prod
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# Log pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
# Log file
logging.file.name=logs/java-dictionary.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n